name: Upload Python Package to PyPI

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow when you push a tag like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # No need to provide credentials as trusted publishing handles authentication
        # Ensure your PyPI project is configured with the correct trusted publisher settings
        repository_url: ${{ github.repository }}
        tag: ${{ github.ref_name }}
